### ISSUE TITLE
error

### ISSUE THREAD

**Issue by IchBinMcd** [qizq1337/Discord-Token-Generator#1]
SyntaxError: Illegal return statement

**Comment by Gercekefsane** [comment]
same error 
SyntaxError: Illegal return statement
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
    at async link (internal/modules/esm/module_job.js:67:21)

**Comment by Sonklol** [comment]
The same happens to me

**Comment by qizq1337** [comment]
it's a leak not my gen, u gotta re add a couple lines of code which is for the adding phone number thingy or just remove it completely. the solvr is good and u can learn from this gen to make ur own bbg

someone bribed me to remove the lines of code cuz his gen would get raped
